### ISSUE TITLE
Run rubocop as a separate CI step

### ISSUE THREAD

**Issue by Mehonoshin** [howtohireme/give-me-poc#530]
**Value**
We want not to allow misstyled code to be committed to repo.

**Possible solution**
Add a separate step and run rubocop in parallel with specs

**Comment by tsrandrei** [comment]
in `Rakefile` adding : 
`
if %w(development test).include? Rails.env
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new

  task(:rubocop_specs_tests).clear
  task rubocop_specs_tests: [:spec,:rubocop]
end
`

**Comment by tsrandrei** [comment]
@Mehonoshin this is what I "implemented" ```.travis.yml```: 

```
- stage: tests
      name: "Rubocop Tests"
      install:
        - gem install bundler -v 1.17.1
        - gem install rubocop
      script:
        - bundle install
        - rubocop
```
but obliviously Rubocop fails as is not having a proper configuration. 
Who we should proceed?
